version: '3.5'

services:

  postgres:
    image: postgres:13
    container_name: postgres
    networks:
      - p8e
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password1
    ports:
      - 5432:5432
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d/

  object-store:
    image: 'us.gcr.io/figure-production/object-store:0.2.0'
    container_name: object-store
    networks:
      - p8e
    env_file:
      - ./common.env
    ports:
      - 8081:8081

  provenance:
    image: provenanceio/provenance:v1.5.0
    container_name: provenance
    networks:
      - p8e
    command: bash -c "cp -rn /home/provenance_seed/* /home/provenance && /usr/bin/provenanced -t --home /home/provenance start"
    ports:
      - 1317:1317
      - 9090:9090
      - 26657:26657
    volumes:
      - ./prov-init:/home/provenance_seed:ro
      - provenance:/home/provenance

volumes:
  postgres:
  object-store:
  provenance:

networks:
  p8e:
    ipam:
      driver: default
      config:
        - subnet: 172.19.10.0/24