version: '3.5'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password1
    ports:
      - 5432:5432
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d/
  object-store:
    image: 'us.gcr.io/figure-production/object-store:0.2.0'
    container_name: object-store
    env_file:
      - ./common.env
    ports:
      - 8080:8080