apiVersion: ctl.figure.com/v1
kind: FigureDeployment
metadata:
  name: service-asset-onboarding
  namespace: onboarding
  labels:
    fd: service-asset-onboarding
spec:
  selector:
    matchLabels:
      fd: service-asset-onboarding
  template:
    metadata:
      labels:
        fd: service-asset-onboarding
    spec:
      kong:
        enabled: true
        services:
          - name: service-asset-onboarding
            proxy:
              path: /
            route:
              path: /service-asset-onboarding
              strip_path: true
              preserve_host: true
            jwt:
              enabled: false
            plugins:
              - plugin: key-auth
                config:
                    key_names:
                      - apikey
                    run_on_preflight: true
              - plugin: acl
                config:
                    allow:
                      - asset-onboarding
      deployment:
        business_unit: figure-tech
        business_product: asset-onboarding
        updateStrategy:
          type: Recreate
        port: 8080
        replicas:
          test: 1
          prod: 1
        image:
          test: us-east1-docker.pkg.dev/figure-development/figure-docker-repo/service-asset-onboarding:latest
          prod: us-east1-docker.pkg.dev/figure-production/figure-docker-repo/service-asset-onboarding:latest
        spring:
          enabled: true
        configMap:
          test:
            PROVENANCE_IS_MAINNET: "false"
            PROVENANCE_CHAIN_ID: "pio-testnet-1"
            PROVENANCE_CHANNEL_URI: "grpc://34.148.39.82:9090"
            PROVENANCE_ASSET_CLASSIFICATION_CONTRACT_NAME: "testassets.pb"
            ASSET_CONTRACT_SPEC_ID: "f97ecc5d-c580-478d-be02-6c1b0c32235f"
            ASSET_SCOPE_SPEC_ID: "551b5eca-921d-4ba7-aded-3966b224f44b"
            ASSET_MANAGER_PUBLIC_KEY: "BDSR5zvFFuLOMgqRH7MhPmpZzz3KlZL0oVQgbIuD4TCbhHUB2MgETo99sRm7xGJWIWGbBgcilc63mD0zxI6zUCo="
            LOAN_STATE_CONTRACT_SPEC_ID: "63a8bb4c-c6e0-4cb5-993b-b134c4b5cbbb"
            LOAN_STATE_SCOPE_SPEC_ID: "2eeada14-07cb-45fe-af6d-fdc48b627817"
          prod:
            PROVENANCE_IS_MAINNET: "true"
            PROVENANCE_CHAIN_ID: "pio-mainnet-1"
            PROVENANCE_CHANNEL_URI: "grpc://34.148.50.57:9090"
            PROVENANCE_ASSET_CLASSIFICATION_CONTRACT_NAME: "asset"
            ASSET_CONTRACT_SPEC_ID: "33bc3ec3-7623-476a-9713-b6efd47e3b74"
            ASSET_SCOPE_SPEC_ID: "1ae489e2-9c42-4d5d-aba9-b9e07de2f87e"
            LOAN_STATE_CONTRACT_SPEC_ID: "23089739-4fd7-4c70-8e32-a6f0500ef4c1"
            LOAN_STATE_SCOPE_SPEC_ID: "2148d958-2b92-440b-b7ff-ed0263583090"
            ASSET_MANAGER_PUBLIC_KEY: "BOWm7T9YcvJNqwi60haIQHoAj8YlyLguirg83cdo3tx3hUqSBMcwZdrLn6gCCYCcF2CtEZBTvFgYc2CmMCU5NQg="
          common:
            JMX_DOMAIN: "tech.figure"
            DOCKET_HOST: "test.figure.tech/service-asset-onboarding"
            DOCKET_CONTACT_NAME: "Figure Technologies"
            DOCKET_CONTACT_URL: "https://figure.tech"
            DOCKET_API_NAME: "Figure Tech Asset Onboarding API"
        readinessProbe:
          path: /service-asset-onboarding/manage/health
          periodSeconds: 3
          initialDelaySeconds: 5
        livenessProbe:
          path: /service-asset-onboarding/manage/health
          periodSeconds: 3
          initialDelaySeconds: 60
        env:
          - name: JAVA_OPTS
            value: -Xms512m -Xmx3g
          - name: OBJECT_STORE_URL
            value: grpc://object-store-v2.core:80
        resources:
          requests:
            cpu: 200m
            memory: 3Gi
          limits:
            cpu: 3000m
            memory: 6Gi
        vault:
          enabled: false
          vault.hashicorp.com/agent-inject: true
          vault.hashicorp.com/log-level: info
