apiVersion: ctl.figure.com/v1
kind: FigureDeployment
metadata:
  name: service-asset-onboarding
  namespace: onboarding
  labels:
    fd: service-asset-onboarding
spec:
  selector:
    matchLabels:
      fd: service-asset-onboarding
  template:
    metadata:
      labels:
        fd: service-asset-onboarding
    spec:
      kong:
        enabled: true
        services:
          - name: service-asset-onboarding
            proxy:
              path: /
            route:
              path: /service-asset-onboarding
              strip_path: true
              preserve_host: true
            jwt:
              enabled: false
      deployment:
        business_unit: figure-tech
        business_product: asset-onboarding
        updateStrategy:
          type: Recreate
        port: 8080
        replicas:
          test: 1
          prod: 1
        image:
          test: us.gcr.io/figure-development/service-asset-onboarding:latest
          prod: us.gcr.io/figure-production/service-asset-onboarding:latest
        spring:
          enabled: true
        configMap:
          test:
            PROVENANCE_IS_MAINNET: "false"
            ASSET_CONTRACT_SPEC_ID: "f97ecc5d-c580-478d-be02-6c1b0c32235f"
            ASSET_SCOPE_SPEC_ID: "551b5eca-921d-4ba7-aded-3966b224f44b"
            ASSET_MANAGER_PUBLIC_KEY: "BDSR5zvFFuLOMgqRH7MhPmpZzz3KlZL0oVQgbIuD4TCbhHUB2MgETo99sRm7xGJWIWGbBgcilc63mD0zxI6zUCo="
          prod:
            PROVENANCE_IS_MAINNET: "true"
            ASSET_CONTRACT_SPEC_ID: ""
            ASSET_SCOPE_SPEC_ID: ""
            ASSET_MANAGER_PUBLIC_KEY: ""
        readinessProbe:
          path: /service-asset-onboarding/manage/health
          periodSeconds: 3
          initialDelaySeconds: 5
        livenessProbe:
          path: /service-asset-onboarding/manage/health
          periodSeconds: 3
          initialDelaySeconds: 60
        env:
          - name: JAVA_OPTS
            value: -Xms512m -Xmx3g
          - name: OBJECT_STORE_URL
            value: grpc://object-store-v2.core:80
        resources:
          requests:
            cpu: 200m
            memory: 3Gi
          limits:
            cpu: 3000m
            memory: 6Gi
        vault:
          enabled: false
          vault.hashicorp.com/agent-inject: true
          vault.hashicorp.com/log-level: info
