apiVersion: ctl.figure.com/v1
kind: FigureDeployment
metadata:
  name: service-asset-onboarding
  namespace: onboarding
  labels:
    fd: service-asset-onboarding
spec:
  selector:
    matchLabels:
      fd: service-asset-onboarding
  template:
    metadata:
      labels:
        fd: service-asset-onboarding
    spec:
      kong:
        enabled: true
        services:
          - name: service-asset-onboarding
            proxy:
              path: /service-asset-onboarding
            route:
              path: /service-asset-onboarding
              strip_path: true
              preserve_host: true
            jwt:
              enabled: true
              isCookieAuth: true
              isFrontEnd: false
              requiredGoogleGroups:
                - team@figure.com
      deployment:
        business_unit: figure-tech
        business_product: asset-onboarding
        port: 8080
        replicas:
          prod: 1
          test: 1
        image:
          prod: us.gcr.io/figure-production/service-asset-onboarding:latest
          test: us.gcr.io/figure-development/service-asset-onboarding:latest
        db:
          enabled: true
          enablePgBouncer: true
          version: "13"
          instance: csp-1-db
          name:
            prod: service-asset-onboarding
            test: service-asset-onboarding
          schema:
            prod: service-asset-onboarding
            test: service-asset-onboarding
          user:
            prod: service-asset-onboarding
            test: service-asset-onboarding
          connectionPoolSize:
            prod: 10
            test: 10
        dbMigration:
          enabled: true
          image:
            prod: us.gcr.io/figure-production/service-asset-onboarding-migrate:latest
            test: us.gcr.io/figure-development/service-asset-onboarding-migrate:latest
        spring:
          enabled: true
        readinessProbe:
          path: /service-asset-onboarding/manage/health
          periodSeconds: 3
          initialDelaySeconds: 5
        livenessProbe:
          path: /service-asset-onboarding/manage/health
          periodSeconds: 3
          initialDelaySeconds: 60
        env:
          - name: JAVA_OPTS
            value: -Xms512m -Xmx3g
        resources:
          requests:
            cpu: 200m
            memory: 3Gi
          limits:
            cpu: 3000m
            memory: 6Gi
        vault:
          enabled: true
          vault.hashicorp.com/agent-inject: true
          vault.hashicorp.com/log-level: info
