name: Build & Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: [ self-hosted, linux ]

    env:
      NEXUS_USER: ${{ secrets.NEXUS_USER }}
      NEXUS_PASS: ${{ secrets.NEXUS_PASS }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Checkout Figure Shared Actions
        uses: actions/checkout@v2-beta
        with:
          repository: FigureTechnologies/shared-actions
          ref: main
          token: ${{ secrets.PAT }}
          path: shared-actions

      - name: Setup Figure Shared Actions Environment
        uses: ./shared-actions/set-env-action
        with:
          prod_ref: refs/heads/master

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Gradle Build
        run: ./gradlew clean build -x test --no-daemon --parallel --refresh-dependencies

      - name: Gradle Unit & Functional Tests
        run: ./gradlew test --no-daemon
