name: Build & Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: [ ubuntu-latest ]

    env:
      NEXUS_USER: ${{ secrets.NEXUS_USER }}
      NEXUS_PASS: ${{ secrets.NEXUS_PASS }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: 'figure-development'
          service_account_key: ${{ secrets.GCP_AUTH_JSON }}

      - name: Google Cloud SDK Configure
        run: gcloud services enable containerregistry.googleapis.com && gcloud auth configure-docker

      - name: Google Cloud SDK Info
        run: gcloud info

      - name: Gradle Build
        run: ./gradlew clean build --no-daemon --parallel --refresh-dependencies
